"""Data filtering pipeline for CPT datasets.

Implements multi-signal filtering for:
- Code files (language, extension, size, quality, generated-code detection)
- Documentation (language detection, boilerplate removal, quality)
- Web text (language, quality score, boilerplate)
- Math content (LaTeX validation, OCR artifact detection)
"""

import logging
import re
from pathlib import PurePosixPath
from typing import Any, Callable, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ==============================================================
# Compiled regex patterns (compile once, reuse)
# ==============================================================

# Autogenerated file patterns
GENERATED_PATTERNS = [
    re.compile(r"_pb2\.py$", re.IGNORECASE),
    re.compile(r"\.pb\.go$", re.IGNORECASE),
    re.compile(r"\.generated\.", re.IGNORECASE),
    re.compile(r"\.auto\.", re.IGNORECASE),
    re.compile(r"\.min\.(js|css)$", re.IGNORECASE),
    re.compile(r"/dist/", re.IGNORECASE),
    re.compile(r"/build/", re.IGNORECASE),
    re.compile(r"/node_modules/", re.IGNORECASE),
    re.compile(r"/__pycache__/", re.IGNORECASE),
    re.compile(r"/\.git/", re.IGNORECASE),
    re.compile(r"/vendor/", re.IGNORECASE),
    re.compile(r"/generated/", re.IGNORECASE),
    re.compile(r"/compiled/", re.IGNORECASE),
]

# Lockfile names
LOCKFILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "cargo.lock",
    "poetry.lock",
    "pipfile.lock",
    "composer.lock",
    "gemfile.lock",
    "packages.lock.json",
    "shrinkwrap.json",
}

# Config files to keep (exceptions to data file exclusion)
CONFIG_KEEP_PATTERNS = [
    "dockerfile",
    "docker-compose",
    "makefile",
    "cmakelists.txt",
    "setup.py",
    "setup.cfg",
    "pyproject.toml",
    "cargo.toml",
    "go.mod",
    "tsconfig.json",
    "webpack.config",
    "vite.config",
    ".eslintrc",
    ".prettierrc",
    "jest.config",
    ".github/workflows/",
    ".circleci/",
    ".travis.yml",
    "jenkinsfile",
]

# Data file extensions to generally exclude
DATA_EXTENSIONS = {
    ".json", ".csv", ".xml", ".yaml", ".yml",
    ".lock", ".map", ".svg", ".png", ".jpg",
    ".jpeg", ".gif", ".ico", ".woff", ".woff2",
    ".ttf", ".eot", ".pb", ".pyc", ".class",
    ".o", ".so", ".dll", ".exe", ".bin",
    ".dat", ".db", ".sqlite", ".log",
}

# Binary/non-text extensions
BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico",
    ".bmp", ".tiff", ".webp", ".mp3", ".mp4",
    ".avi", ".mov", ".flac", ".ogg", ".wav",
    ".zip", ".tar", ".gz", ".bz2", ".xz",
    ".rar", ".7z", ".pdf", ".doc", ".docx",
    ".ppt", ".pptx", ".xls", ".xlsx",
    ".woff", ".woff2", ".ttf", ".eot",
    ".pyc", ".pyo", ".class", ".o", ".so",
    ".dll", ".exe", ".bin", ".dat",
}

# Web boilerplate phrases (for FineWeb-HQ filtering)
WEB_BOILERPLATE = [
    "cookie", "privacy policy", "terms of service",
    "subscribe to newsletter", "sign up for",
    "click here to", "all rights reserved",
    "copyright ©", "accept cookies", "manage consent",
    "we use cookies", "cookie settings",
]

# OCR artifact patterns (for math content)
OCR_PATTERNS = re.compile(
    r"[^\x00-\x7F]{10,}|"  # Long non-ASCII sequences
    r"[\x00-\x08\x0e-\x1f]{3,}|"  # Control characters
    r"(.)\1{10,}|"  # Repeated characters
    r"[|]{5,}"  # Repeated pipes (common OCR artifact)
)


class FilterStats:
    """Track filtering statistics for reporting."""

    def __init__(self):
        self.total_seen = 0
        self.total_passed = 0
        self.reasons: Dict[str, int] = {}

    def record_pass(self):
        self.total_seen += 1
        self.total_passed += 1

    def record_reject(self, reason: str):
        self.total_seen += 1
        self.reasons[reason] = self.reasons.get(reason, 0) + 1

    @property
    def pass_rate(self) -> float:
        if self.total_seen == 0:
            return 0.0
        return self.total_passed / self.total_seen

    def summary(self) -> Dict[str, Any]:
        return {
            "total_seen": self.total_seen,
            "total_passed": self.total_passed,
            "pass_rate": f"{self.pass_rate:.2%}",
            "rejection_reasons": dict(
                sorted(self.reasons.items(), key=lambda x: -x[1])
            ),
        }


# ==============================================================
# Code Filtering
# ==============================================================

def is_generated_file(file_path: str) -> bool:
    """Check if a file path matches autogenerated patterns."""
    for pattern in GENERATED_PATTERNS:
        if pattern.search(file_path):
            return True
    return False


def is_lockfile(file_path: str) -> bool:
    """Check if a file is a lockfile."""
    basename = file_path.rsplit("/", 1)[-1].lower() if "/" in file_path else file_path.lower()
    return basename in LOCKFILES


def is_config_file(file_path: str) -> bool:
    """Check if a file is a useful config file (should be kept)."""
    path_lower = file_path.lower()
    basename = path_lower.rsplit("/", 1)[-1] if "/" in path_lower else path_lower
    for pattern in CONFIG_KEEP_PATTERNS:
        if basename.startswith(pattern) or pattern in path_lower:
            return True
    return False


def is_data_file(file_path: str) -> bool:
    """Check if a file is a data/config dump (generally exclude)."""
    ext = PurePosixPath(file_path).suffix.lower()
    if ext in DATA_EXTENSIONS:
        # Exception: keep config files
        return not is_config_file(file_path)
    return False


def compute_alphanumeric_ratio(text: str) -> float:
    """Compute the ratio of alphanumeric characters in text."""
    if not text:
        return 0.0
    alnum = sum(1 for c in text if c.isalnum())
    return alnum / len(text)


def compute_line_stats(text: str) -> Dict[str, Any]:
    """Compute line-level statistics for a code file."""
    lines = text.split("\n")
    num_lines = len(lines)
    max_line_len = max((len(line) for line in lines), default=0)
    avg_line_len = sum(len(line) for line in lines) / max(num_lines, 1)

    # Count blank lines
    blank_lines = sum(1 for line in lines if not line.strip())

    return {
        "num_lines": num_lines,
        "max_line_len": max_line_len,
        "avg_line_len": avg_line_len,
        "blank_line_ratio": blank_lines / max(num_lines, 1),
    }


def filter_code_sample(
    sample: Dict[str, Any],
    config: Dict[str, Any],
    stats: Optional[FilterStats] = None,
) -> Optional[Dict[str, Any]]:
    """Apply all code filtering rules to a sample.

    Args:
        sample: Dict with 'text', 'file_path', 'language', etc.
        config: File filter configuration from dataset_config.yaml.
        stats: Optional FilterStats to record pass/reject.

    Returns:
        The sample if it passes all filters, None otherwise.
    """
    text = sample.get("text", "")
    file_path = sample.get("file_path", "")
    size_bytes = sample.get("size_bytes", len(text.encode("utf-8", errors="replace")))

    file_filters = config.get("file_filters", {})

    # --- Size filters ---
    min_size = file_filters.get("min_file_size_bytes", 100)
    max_size = file_filters.get("max_file_size_bytes", 1_000_000)
    if size_bytes < min_size:
        if stats:
            stats.record_reject("too_small")
        return None
    if size_bytes > max_size:
        if stats:
            stats.record_reject("too_large")
        return None

    # --- Generated file detection ---
    if is_generated_file(file_path):
        if stats:
            stats.record_reject("generated_file")
        return None

    # --- Lockfile detection ---
    if is_lockfile(file_path):
        if stats:
            stats.record_reject("lockfile")
        return None

    # --- Data file detection ---
    if is_data_file(file_path):
        if stats:
            stats.record_reject("data_file")
        return None

    # --- Extension exclusion ---
    ext = PurePosixPath(file_path).suffix.lower()
    exclude_exts = set(file_filters.get("exclude_extensions", []))
    if ext in exclude_exts and not is_config_file(file_path):
        if stats:
            stats.record_reject("excluded_extension")
        return None

    # --- Alphanumeric ratio ---
    min_alnum = file_filters.get("min_alphanumeric_ratio", 0.25)
    alnum_ratio = compute_alphanumeric_ratio(text)
    if alnum_ratio < min_alnum:
        if stats:
            stats.record_reject("low_alphanumeric_ratio")
        return None

    # --- Line stats ---
    line_stats = compute_line_stats(text)
    min_lines = file_filters.get("min_line_count", 3)
    max_lines = file_filters.get("max_line_count", 10000)
    max_line_len = file_filters.get("max_line_length", 1000)

    if line_stats["num_lines"] < min_lines:
        if stats:
            stats.record_reject("too_few_lines")
        return None
    if line_stats["num_lines"] > max_lines:
        if stats:
            stats.record_reject("too_many_lines")
        return None
    if line_stats["max_line_len"] > max_line_len:
        # Check if it's just one or two very long lines (common in minified code)
        long_lines = sum(1 for line in text.split("\n") if len(line) > max_line_len)
        if long_lines > 2:
            if stats:
                stats.record_reject("lines_too_long")
            return None

    # --- Empty/whitespace-only ---
    if not text.strip():
        if stats:
            stats.record_reject("empty")
        return None

    if stats:
        stats.record_pass()

    # Add computed metadata
    sample["alnum_ratio"] = alnum_ratio
    sample["num_lines"] = line_stats["num_lines"]
    return sample


# ==============================================================
# Documentation Filtering
# ==============================================================

def filter_doc_sample(
    sample: Dict[str, Any],
    config: Dict[str, Any],
    lang_detector: Optional[Callable] = None,
    stats: Optional[FilterStats] = None,
) -> Optional[Dict[str, Any]]:
    """Apply documentation filtering rules.

    Args:
        sample: Dict with 'text', 'file_path', etc.
        config: Doc filter configuration.
        lang_detector: Optional callable(text) -> (lang, confidence).
        stats: Optional FilterStats.

    Returns:
        The sample if it passes, None otherwise.
    """
    text = sample.get("text", "")
    doc_filters = config.get("doc_filters", {})

    # --- Length filters ---
    min_len = doc_filters.get("min_length_chars", 200)
    max_len = doc_filters.get("max_length_chars", 500_000)
    if len(text) < min_len:
        if stats:
            stats.record_reject("doc_too_short")
        return None
    if len(text) > max_len:
        if stats:
            stats.record_reject("doc_too_long")
        return None

    # --- Alphanumeric ratio ---
    min_alnum = doc_filters.get("min_alphanumeric_ratio", 0.50)
    alnum_ratio = compute_alphanumeric_ratio(text)
    if alnum_ratio < min_alnum:
        if stats:
            stats.record_reject("doc_low_alnum")
        return None

    # --- Language detection ---
    lang_cfg = doc_filters.get("language_detection", {})
    if lang_cfg.get("enabled", False) and lang_detector is not None:
        min_conf = lang_cfg.get("min_english_confidence", 0.70)
        lang, confidence = lang_detector(text)
        if lang != "en" or confidence < min_conf:
            if stats:
                stats.record_reject("non_english_doc")
            return None

    # --- Boilerplate detection ---
    max_boilerplate = doc_filters.get("max_boilerplate_ratio", 0.4)
    lines = text.split("\n")
    if len(lines) > 5:
        # Simple boilerplate: count repeated lines
        from collections import Counter
        line_counts = Counter(line.strip() for line in lines if line.strip())
        total_lines = sum(line_counts.values())
        repeated = sum(c - 1 for c in line_counts.values() if c > 1)
        if total_lines > 0 and (repeated / total_lines) > max_boilerplate:
            if stats:
                stats.record_reject("doc_boilerplate")
            return None

    if stats:
        stats.record_pass()

    return sample


# ==============================================================
# Web Text Filtering (FineWeb-HQ)
# ==============================================================

def filter_web_sample(
    sample: Dict[str, Any],
    config: Dict[str, Any],
    lang_detector: Optional[Callable] = None,
    stats: Optional[FilterStats] = None,
) -> Optional[Dict[str, Any]]:
    """Apply web text filtering rules.

    Args:
        sample: Dict with 'text', 'url', 'quality_score', etc.
        config: Web filter configuration.
        lang_detector: Optional callable(text) -> (lang, confidence).
        stats: Optional FilterStats.

    Returns:
        The sample if it passes, None otherwise.
    """
    text = sample.get("text", "")
    filters = config.get("filters", {})

    # --- Length ---
    min_len = filters.get("min_length_chars", 200)
    max_len = filters.get("max_length_chars", 200_000)
    if len(text) < min_len:
        if stats:
            stats.record_reject("web_too_short")
        return None
    if len(text) > max_len:
        if stats:
            stats.record_reject("web_too_long")
        return None

    # --- Alphanumeric ratio ---
    min_alnum = filters.get("min_alphanumeric_ratio", 0.60)
    if compute_alphanumeric_ratio(text) < min_alnum:
        if stats:
            stats.record_reject("web_low_alnum")
        return None

    # --- Quality score ---
    min_quality = filters.get("min_quality_score")
    if min_quality is not None:
        score = sample.get("quality_score")
        if score is not None and score < min_quality:
            if stats:
                stats.record_reject("web_low_quality")
            return None

    # --- Language detection ---
    lang_cfg = filters.get("language_detection", {})
    if lang_cfg.get("enabled", False) and lang_detector is not None:
        min_conf = lang_cfg.get("min_english_confidence", 0.80)
        lang, confidence = lang_detector(text)
        if lang != "en" or confidence < min_conf:
            if stats:
                stats.record_reject("non_english_web")
            return None

    # --- Web boilerplate ---
    if filters.get("remove_boilerplate", True):
        text_lower = text.lower()
        boilerplate_count = sum(
            1 for phrase in WEB_BOILERPLATE if phrase in text_lower
        )
        # If too many boilerplate phrases relative to text length
        if boilerplate_count > 3 and boilerplate_count / max(len(text) / 500, 1) > 0.5:
            if stats:
                stats.record_reject("web_boilerplate")
            return None

    if stats:
        stats.record_pass()

    return sample


# ==============================================================
# Math Content Filtering
# ==============================================================

def filter_math_sample(
    sample: Dict[str, Any],
    config: Dict[str, Any],
    lang_detector: Optional[Callable] = None,
    stats: Optional[FilterStats] = None,
) -> Optional[Dict[str, Any]]:
    """Apply math content filtering rules.

    Args:
        sample: Dict with 'text', 'url', 'metadata', etc.
        config: Math filter configuration.
        lang_detector: Optional callable(text) -> (lang, confidence).
        stats: Optional FilterStats.

    Returns:
        The sample if it passes, None otherwise.
    """
    text = sample.get("text", "")
    filters = config.get("filters", {})

    # --- Length ---
    min_len = filters.get("min_length_chars", 100)
    max_len = filters.get("max_length_chars", 200_000)
    if len(text) < min_len:
        if stats:
            stats.record_reject("math_too_short")
        return None
    if len(text) > max_len:
        if stats:
            stats.record_reject("math_too_long")
        return None

    math_quality = filters.get("math_quality", {})

    # --- OCR artifacts ---
    if math_quality.get("reject_ocr_artifacts", True):
        if OCR_PATTERNS.search(text):
            if stats:
                stats.record_reject("math_ocr_artifact")
            return None

    # --- Broken LaTeX ---
    if math_quality.get("reject_broken_latex", True):
        # Simple heuristic: check for unmatched $ or \begin without \end
        dollar_count = text.count("$") - text.count("\\$")
        if dollar_count % 2 != 0 and dollar_count > 5:
            if stats:
                stats.record_reject("math_broken_latex")
            return None

        begin_count = text.count("\\begin{")
        end_count = text.count("\\end{")
        if begin_count > 0 and abs(begin_count - end_count) > 2:
            if stats:
                stats.record_reject("math_unmatched_env")
            return None

    # --- Repeated content ---
    max_repeated = math_quality.get("max_repeated_line_ratio", 0.3)
    lines = [line.strip() for line in text.split("\n") if line.strip()]
    if len(lines) > 5:
        from collections import Counter
        line_counts = Counter(lines)
        repeated = sum(c - 1 for c in line_counts.values() if c > 1)
        if repeated / max(len(lines), 1) > max_repeated:
            if stats:
                stats.record_reject("math_repeated_content")
            return None

    # --- Language detection ---
    lang_cfg = filters.get("language_detection", {})
    if lang_cfg.get("enabled", False) and lang_detector is not None:
        min_conf = lang_cfg.get("min_english_confidence", 0.60)
        lang, confidence = lang_detector(text)
        if lang != "en" or confidence < min_conf:
            if stats:
                stats.record_reject("non_english_math")
            return None

    if stats:
        stats.record_pass()

    return sample


# ==============================================================
# Vault (Function-Level) Filtering
# ==============================================================

def filter_vault_sample(
    sample: Dict[str, Any],
    config: Dict[str, Any],
    stats: Optional[FilterStats] = None,
) -> Optional[Dict[str, Any]]:
    """Apply filtering rules for The Vault function-level code.

    Args:
        sample: Dict with 'text', 'language', 'identifier', etc.
        config: Vault filter configuration.
        stats: Optional FilterStats.

    Returns:
        The sample if it passes, None otherwise.
    """
    text = sample.get("text", "")
    filters = config.get("filters", {})

    # --- Length ---
    min_len = filters.get("min_code_length_chars", 50)
    max_len = filters.get("max_code_length_chars", 50_000)
    if len(text) < min_len:
        if stats:
            stats.record_reject("vault_too_short")
        return None
    if len(text) > max_len:
        if stats:
            stats.record_reject("vault_too_long")
        return None

    # --- Alphanumeric ratio ---
    min_alnum = filters.get("min_alphanumeric_ratio", 0.30)
    if compute_alphanumeric_ratio(text) < min_alnum:
        if stats:
            stats.record_reject("vault_low_alnum")
        return None

    # --- Empty identifier ---
    if not sample.get("identifier", "").strip():
        if stats:
            stats.record_reject("vault_no_identifier")
        return None

    if stats:
        stats.record_pass()

    return sample


# ==============================================================
# Language Detection
# ==============================================================

class LanguageDetector:
    """Lightweight language detector using fastText.

    Falls back to simple heuristics if fastText is not available.
    """

    def __init__(self, model_path: Optional[str] = None):
        """Initialize the language detector.

        Args:
            model_path: Path to fastText lid model. If None, will try
                       to download lid.176.bin automatically.
        """
        self.model = None
        self._load_model(model_path)

    def _load_model(self, model_path: Optional[str] = None):
        """Try to load fastText language detection model."""
        try:
            import fasttext

            if model_path and Path(model_path).exists():
                self.model = fasttext.load_model(model_path)
            else:
                # Try common locations
                for path in [
                    "lid.176.bin",
                    "/tmp/lid.176.bin",
                    Path.home() / ".cache" / "fasttext" / "lid.176.bin",
                ]:
                    if Path(path).exists():
                        self.model = fasttext.load_model(str(path))
                        break

            if self.model is None:
                logger.warning(
                    "fastText lid model not found. Language detection will "
                    "use fallback heuristics. Download lid.176.bin from "
                    "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin"
                )
        except ImportError:
            logger.warning(
                "fastText not installed. Language detection will use "
                "fallback heuristics. Install with: pip install fasttext-wheel"
            )

    def detect(self, text: str) -> Tuple[str, float]:
        """Detect the language of a text.

        Args:
            text: Input text.

        Returns:
            Tuple of (language_code, confidence).
        """
        if not text or len(text.strip()) < 20:
            return ("unknown", 0.0)

        if self.model is not None:
            # fastText expects single-line input
            clean = text.replace("\n", " ")[:5000]
            predictions = self.model.predict(clean, k=1)
            label = predictions[0][0].replace("__label__", "")
            confidence = float(predictions[1][0])
            return (label, confidence)

        # Fallback: simple heuristic based on character distribution
        return self._fallback_detect(text)

    def _fallback_detect(self, text: str) -> Tuple[str, float]:
        """Simple fallback language detection using character analysis."""
        # Count ASCII vs non-ASCII
        ascii_chars = sum(1 for c in text if ord(c) < 128)
        total_chars = len(text)

        if total_chars == 0:
            return ("unknown", 0.0)

        ascii_ratio = ascii_chars / total_chars

        # High ASCII ratio suggests English or code
        if ascii_ratio > 0.95:
            return ("en", 0.7)
        elif ascii_ratio > 0.80:
            return ("en", 0.5)
        else:
            return ("unknown", 0.3)

    def __call__(self, text: str) -> Tuple[str, float]:
        """Convenience: make the detector callable."""
        return self.detect(text)
